// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC

import { useState, useCallback } from "react";
import type {
  BugReportData,
  BugReportForm,
  BugReportStep,
  LogSourceState,
} from "./types";

const INITIAL_FORM: BugReportForm = {
  title: "",
  description: "",
  steps: "",
  expected: "",
  actual: "",
};

const INITIAL_SOURCES: LogSourceState[] = [
  { label: "Backend (Django) logs", key: "backend_log", status: "pending" },
  { label: "FastAPI inference logs", key: "fastapi_log", status: "pending" },
  {
    label: "Per-deployment FastAPI logs",
    key: "fastapi_deployment_logs",
    status: "pending",
  },
  {
    label: "Docker control service logs",
    key: "docker_control_log",
    status: "pending",
  },
  { label: "Startup logs", key: "startup_log", status: "pending" },
  { label: "Agent logs", key: "agent_log", status: "pending" },
  {
    label: "Inference model run logs",
    key: "inference_run_logs",
    status: "pending",
  },
  {
    label: "Inference docker server logs",
    key: "inference_docker_server_logs",
    status: "pending",
  },
  { label: "tt-smi hardware data", key: "tt_smi", status: "pending" },
  { label: "Deployment history", key: "deployments", status: "pending" },
  {
    label: "Current deployed models (snapshot)",
    key: "current_models",
    status: "pending",
  },
];

function makeDiagnosticsRef(): string {
  const suffix =
    typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? crypto.randomUUID().replace(/-/g, "").slice(0, 12)
      : `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 10)}`;
  return `ttbr-${suffix}`;
}

/** Concise body for GitHub issues — keeps well under 65 KB GitHub body limit */
function buildIssueBody(form: BugReportForm, diagnosticsRef: string): string {
  const now = new Date();
  return `## Bug Report

**Date:** ${now.toLocaleDateString()} ${now.toLocaleTimeString()}
**URL:** ${window.location.href}
**ZIP / diagnostics reference:** \`${diagnosticsRef}\`

Match this issue to the diagnostics bundle: the downloaded ZIP from TT-Studio uses this reference in its filename. Paste it in a follow-up comment if you rename the file.

### Description
${form.description || "_Not provided_"}

### Steps to Reproduce
${form.steps || "_Not provided_"}

### Expected Behavior
${form.expected || "_Not provided_"}

### Actual Behavior
${form.actual || "_Not provided_"}

---

TT-Studio diagnostics were collected separately and intentionally are not embedded in this GitHub issue to keep the report short and avoid oversized issue URLs/bodies.

Collected diagnostics include backend and tt-inference-server logs, deployment history, inference artifacts, tt-smi hardware data, and a current deployed-models snapshot (see current_models.json in the ZIP).

**Please attach the diagnostics ZIP to this GitHub issue** after you create it: in TT-Studio use **Download Logs as ZIP** (step 3), then on the GitHub issue attach that file (GitHub does not accept large bodies via URL).

*Auto-generated by TT-Studio Bug Reporter*`;
}

/** Full verbose markdown for clipboard copy */
function buildFullMarkdown(
  form: BugReportForm,
  data: BugReportData,
  diagnosticsRef: string
): string {
  const now = new Date();

  const renderEntries = (entries: { file: string | null; content: string }[]) =>
    entries.length === 0
      ? "_None found_"
      : entries
          .map(
            (e) =>
              `**${e.file ? e.file.split("/").pop() : "unknown"}**\n\`\`\`\n${e.content}\n\`\`\``
          )
          .join("\n\n");

  return `## Bug Report (Full)

**Date:** ${now.toLocaleDateString()} ${now.toLocaleTimeString()}
**URL:** ${window.location.href}
**User Agent:** ${navigator.userAgent}
**ZIP / diagnostics reference:** \`${diagnosticsRef}\`

### Description
${form.description || "_Not provided_"}

### Steps to Reproduce
${form.steps || "_Not provided_"}

### Expected Behavior
${form.expected || "_Not provided_"}

### Actual Behavior
${form.actual || "_Not provided_"}

---

### Hardware (tt-smi)
\`\`\`json
${JSON.stringify(data.tt_smi, null, 2)}
\`\`\`

### Deployment History
\`\`\`json
${JSON.stringify(data.deployments, null, 2)}
\`\`\`

### Current deployed models (snapshot)
\`\`\`json
${JSON.stringify(data.current_models, null, 2)}
\`\`\`

### Backend Log
\`\`\`
${data.backend_log.content}
\`\`\`

### FastAPI Log
\`\`\`
${data.fastapi_log.content}
\`\`\`

### Per-Deployment FastAPI Logs
${renderEntries(data.fastapi_deployment_logs)}

### Docker Control Service Log
\`\`\`
${data.docker_control_log.content}
\`\`\`

### Startup Log
\`\`\`
${data.startup_log.content}
\`\`\`

### Agent Log
\`\`\`
${data.agent_log.content}
\`\`\`

### Inference Model Run Logs
${renderEntries(data.inference_run_logs)}

### Inference Docker Server Logs
${renderEntries(data.inference_docker_server_logs)}

---
*Auto-generated by TT-Studio Bug Reporter*`;
}

export function useBugReport() {
  const [step, setStep] = useState<BugReportStep>("form");
  const [form, setForm] = useState<BugReportForm>(INITIAL_FORM);
  const [sources, setSources] = useState<LogSourceState[]>(INITIAL_SOURCES);
  const [data, setData] = useState<BugReportData | null>(null);
  /** Stable id for matching a GitHub issue to one downloaded diagnostics ZIP. */
  const [diagnosticsRef, setDiagnosticsRef] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [issueResult, setIssueResult] = useState<{
    url?: string;
    issue_url?: string;
    issue_number?: number;
    created_via_api?: boolean;
  } | null>(null);

  const setSourceStatus = useCallback(
    (key: string, status: LogSourceState["status"]) => {
      setSources((prev) =>
        prev.map((s) => (s.key === key ? { ...s, status } : s))
      );
    },
    []
  );

  const startCollection = useCallback(async () => {
    setStep("collecting");
    setDiagnosticsRef(null);
    setSources(INITIAL_SOURCES.map((s) => ({ ...s, status: "loading" })));

    try {
      const response = await fetch("/logs-api/bug-report/");
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const collected: BugReportData = await response.json();
      setData(collected);
      setDiagnosticsRef(makeDiagnosticsRef());

      // Mark sources as done/error based on actual content
      setSources(
        INITIAL_SOURCES.map((s) => {
          const value = (collected as unknown as Record<string, unknown>)[s.key];
          let status: LogSourceState["status"] = "done";
          if (value === undefined || value === null) {
            status = "error";
          } else if (
            typeof value === "object" &&
            !Array.isArray(value) &&
            "error" in (value as object)
          ) {
            status = "error";
          } else if (Array.isArray(value) && value.length === 0) {
            status = "done"; // empty is ok — just nothing to show
          }
          return { ...s, status };
        })
      );

      setStep("actions");
    } catch (err) {
      console.error("Bug report collection failed:", err);
      setDiagnosticsRef(null);
      setSources((prev) => prev.map((s) => ({ ...s, status: "error" })));
    }
  }, []);

  const downloadZip = useCallback(async () => {
    const response = await fetch("/logs-api/bug-report/download/");
    if (!response.ok) throw new Error(`Download failed: HTTP ${response.status}`);
    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const slug =
      diagnosticsRef ??
      new Date().toISOString().replace(/[:.]/g, "-");
    a.download = `tt-studio-logs-${slug}.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [diagnosticsRef]);

  const createGitHubIssue = useCallback(async () => {
    if (!data) return;
    const ref = diagnosticsRef ?? makeDiagnosticsRef();
    if (!diagnosticsRef) setDiagnosticsRef(ref);
    setIsSubmitting(true);
    setIssueResult(null);
    try {
      const trimmedTitle = form.title.trim();
      const dateStr = new Date().toLocaleDateString();
      // Always read as a TT-Studio bug report in the tracker (not just a bare user phrase + tag).
      const title =
        trimmedTitle === ""
          ? `TT-Studio bug report [${ref}] (${dateStr})`
          : trimmedTitle.includes(ref)
            ? trimmedTitle
            : `TT-Studio bug report — ${trimmedTitle} [${ref}]`;
      const body = buildIssueBody(form, ref);

      const response = await fetch("/logs-api/github-issue/", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title,
          body,
          labels: ["bug", "auto-generated"],
        }),
      });

      const result = await response.json();

      if (result.created_via_api) {
        setIssueResult(result);
      } else if (result.url) {
        // No PAT — open browser URL
        window.open(result.url, "_blank");
        setIssueResult(result);
      } else {
        throw new Error(result.error ?? "Unknown error");
      }
    } catch (err) {
      console.error("Failed to create GitHub issue:", err);
      throw err;
    } finally {
      setIsSubmitting(false);
    }
  }, [data, diagnosticsRef, form]);

  const copyToClipboard = useCallback(async () => {
    if (!data) return;
    const ref = diagnosticsRef ?? makeDiagnosticsRef();
    const text = buildFullMarkdown(form, data, ref);
    await navigator.clipboard.writeText(text);
  }, [data, diagnosticsRef, form]);

  const reset = useCallback(() => {
    setStep("form");
    setForm(INITIAL_FORM);
    setSources(INITIAL_SOURCES);
    setData(null);
    setDiagnosticsRef(null);
    setIsSubmitting(false);
    setIssueResult(null);
  }, []);

  return {
    step,
    form,
    setForm,
    sources,
    data,
    diagnosticsRef,
    isSubmitting,
    issueResult,
    startCollection,
    downloadZip,
    createGitHubIssue,
    copyToClipboard,
    reset,
  };
}
