// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC

import { useState, useCallback } from "react";
import type {
  BugReportData,
  BugReportForm,
  BugReportStep,
  LogSourceState,
} from "./types";

const INITIAL_FORM: BugReportForm = {
  title: "",
  description: "",
  steps: "",
  expected: "",
  actual: "",
};

const INITIAL_SOURCES: LogSourceState[] = [
  { label: "Backend (Django) logs", key: "backend_log", status: "pending" },
  { label: "FastAPI inference logs", key: "fastapi_log", status: "pending" },
  {
    label: "Per-deployment FastAPI logs",
    key: "fastapi_deployment_logs",
    status: "pending",
  },
  {
    label: "Docker control service logs",
    key: "docker_control_log",
    status: "pending",
  },
  { label: "Startup logs", key: "startup_log", status: "pending" },
  { label: "Agent logs", key: "agent_log", status: "pending" },
  {
    label: "Inference model run logs",
    key: "inference_run_logs",
    status: "pending",
  },
  {
    label: "Inference docker server logs",
    key: "inference_docker_server_logs",
    status: "pending",
  },
  { label: "tt-smi hardware data", key: "tt_smi", status: "pending" },
  { label: "Deployment history", key: "deployments", status: "pending" },
];

function truncate(text: string, maxChars: number): string {
  if (text.length <= maxChars) return text;
  return text.slice(0, maxChars) + "\n... (truncated — full logs in ZIP download)";
}

function ttSmiSummary(data: BugReportData): string {
  const raw = data.tt_smi;
  if (!raw || "error" in raw) return (raw as { error?: string })?.error ?? "Unavailable";
  // Pull out key scalar fields only — skip nested objects to stay compact
  const devices = Array.isArray(raw.device_info) ? raw.device_info : [];
  if (devices.length === 0) return JSON.stringify(raw, null, 2).slice(0, 800);
  return (devices as Record<string, unknown>[])
    .map((d, i) => {
      const telem = (d.telemetry ?? {}) as Record<string, unknown>;
      return `Device ${i}: board_type=${d.board_type ?? "?"} temp=${telem.asic_temperature ?? "?"}°C power=${telem.power ?? "?"}W voltage=${telem.voltage ?? "?"}V`;
    })
    .join("\n");
}

function deploymentSummary(data: BugReportData): string {
  if (!Array.isArray(data.deployments) || data.deployments.length === 0)
    return "No deployments";
  return (data.deployments as Record<string, unknown>[])
    .slice(0, 5)
    .map((d) => `- ${d.model_name ?? "?"} | status=${d.status ?? "?"} | deployed=${d.deployed_at ?? "?"}`)
    .join("\n");
}

/** Concise body for GitHub issues — keeps well under 65 KB GitHub body limit */
function buildIssueBody(form: BugReportForm, data: BugReportData): string {
  const now = new Date();
  return `## Bug Report

**Date:** ${now.toLocaleDateString()} ${now.toLocaleTimeString()}
**URL:** ${window.location.href}

### Description
${form.description || "_Not provided_"}

### Steps to Reproduce
${form.steps || "_Not provided_"}

### Expected Behavior
${form.expected || "_Not provided_"}

### Actual Behavior
${form.actual || "_Not provided_"}

---

### Hardware (tt-smi summary)
\`\`\`
${ttSmiSummary(data)}
\`\`\`

### Deployed Models
${deploymentSummary(data)}

### FastAPI Log (last ~50 lines)
\`\`\`
${truncate(data.fastapi_log.content, 2000)}
\`\`\`

### Backend Log (last ~50 lines)
\`\`\`
${truncate(data.backend_log.content, 2000)}
\`\`\`

### Agent Log (last ~50 lines)
\`\`\`
${truncate(data.agent_log.content, 1500)}
\`\`\`

---
> Full logs (all services, inference artifacts, tt-smi JSON, deployment history) are available via **Download Logs as ZIP** in TT-Studio.

*Auto-generated by TT-Studio Bug Reporter*`;
}

/** Full verbose markdown for clipboard copy */
function buildFullMarkdown(form: BugReportForm, data: BugReportData): string {
  const now = new Date();

  const renderEntries = (entries: { file: string | null; content: string }[]) =>
    entries.length === 0
      ? "_None found_"
      : entries
          .map(
            (e) =>
              `**${e.file ? e.file.split("/").pop() : "unknown"}**\n\`\`\`\n${e.content}\n\`\`\``
          )
          .join("\n\n");

  return `## Bug Report (Full)

**Date:** ${now.toLocaleDateString()} ${now.toLocaleTimeString()}
**URL:** ${window.location.href}
**User Agent:** ${navigator.userAgent}

### Description
${form.description || "_Not provided_"}

### Steps to Reproduce
${form.steps || "_Not provided_"}

### Expected Behavior
${form.expected || "_Not provided_"}

### Actual Behavior
${form.actual || "_Not provided_"}

---

### Hardware (tt-smi)
\`\`\`json
${JSON.stringify(data.tt_smi, null, 2)}
\`\`\`

### Deployment History
\`\`\`json
${JSON.stringify(data.deployments, null, 2)}
\`\`\`

### Backend Log
\`\`\`
${data.backend_log.content}
\`\`\`

### FastAPI Log
\`\`\`
${data.fastapi_log.content}
\`\`\`

### Per-Deployment FastAPI Logs
${renderEntries(data.fastapi_deployment_logs)}

### Docker Control Service Log
\`\`\`
${data.docker_control_log.content}
\`\`\`

### Startup Log
\`\`\`
${data.startup_log.content}
\`\`\`

### Agent Log
\`\`\`
${data.agent_log.content}
\`\`\`

### Inference Model Run Logs
${renderEntries(data.inference_run_logs)}

### Inference Docker Server Logs
${renderEntries(data.inference_docker_server_logs)}

---
*Auto-generated by TT-Studio Bug Reporter*`;
}

export function useBugReport() {
  const [step, setStep] = useState<BugReportStep>("form");
  const [form, setForm] = useState<BugReportForm>(INITIAL_FORM);
  const [sources, setSources] = useState<LogSourceState[]>(INITIAL_SOURCES);
  const [data, setData] = useState<BugReportData | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [issueResult, setIssueResult] = useState<{
    url?: string;
    issue_url?: string;
    issue_number?: number;
    created_via_api?: boolean;
  } | null>(null);

  const setSourceStatus = useCallback(
    (key: string, status: LogSourceState["status"]) => {
      setSources((prev) =>
        prev.map((s) => (s.key === key ? { ...s, status } : s))
      );
    },
    []
  );

  const startCollection = useCallback(async () => {
    setStep("collecting");
    setSources(INITIAL_SOURCES.map((s) => ({ ...s, status: "loading" })));

    try {
      const response = await fetch("/logs-api/bug-report/");
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const collected: BugReportData = await response.json();
      setData(collected);

      // Mark sources as done/error based on actual content
      setSources(
        INITIAL_SOURCES.map((s) => {
          const value = (collected as unknown as Record<string, unknown>)[s.key];
          let status: LogSourceState["status"] = "done";
          if (value === undefined || value === null) {
            status = "error";
          } else if (
            typeof value === "object" &&
            !Array.isArray(value) &&
            "error" in (value as object)
          ) {
            status = "error";
          } else if (Array.isArray(value) && value.length === 0) {
            status = "done"; // empty is ok — just nothing to show
          }
          return { ...s, status };
        })
      );

      setStep("actions");
    } catch (err) {
      console.error("Bug report collection failed:", err);
      setSources((prev) => prev.map((s) => ({ ...s, status: "error" })));
    }
  }, []);

  const downloadZip = useCallback(async () => {
    const response = await fetch("/logs-api/bug-report/download/");
    if (!response.ok) throw new Error(`Download failed: HTTP ${response.status}`);
    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    a.download = `tt-studio-logs-${timestamp}.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, []);

  const createGitHubIssue = useCallback(async () => {
    if (!data) return;
    setIsSubmitting(true);
    setIssueResult(null);
    try {
      const title =
        form.title.trim() ||
        `[Bug Report] Issue in TT-Studio (${new Date().toLocaleDateString()})`;
      const body = buildIssueBody(form, data);

      const response = await fetch("/logs-api/github-issue/", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title,
          body,
          labels: ["bug", "auto-generated"],
        }),
      });

      const result = await response.json();

      if (result.created_via_api) {
        setIssueResult(result);
      } else if (result.url) {
        // No PAT — open browser URL
        window.open(result.url, "_blank");
        setIssueResult(result);
      } else {
        throw new Error(result.error ?? "Unknown error");
      }
    } catch (err) {
      console.error("Failed to create GitHub issue:", err);
      throw err;
    } finally {
      setIsSubmitting(false);
    }
  }, [data, form]);

  const copyToClipboard = useCallback(async () => {
    if (!data) return;
    const text = buildFullMarkdown(form, data);
    await navigator.clipboard.writeText(text);
  }, [data, form]);

  const reset = useCallback(() => {
    setStep("form");
    setForm(INITIAL_FORM);
    setSources(INITIAL_SOURCES);
    setData(null);
    setIsSubmitting(false);
    setIssueResult(null);
  }, []);

  return {
    step,
    form,
    setForm,
    sources,
    data,
    isSubmitting,
    issueResult,
    startCollection,
    downloadZip,
    createGitHubIssue,
    copyToClipboard,
    reset,
  };
}
