# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: © 2024 Tenstorrent AI ULC

LINCOLN_TOWN_CAR = """
The Lincoln Town Car is a model line of full-size luxury sedans that was marketed by the Lincoln division of the American automaker Ford Motor Company. Deriving its name from a limousine body style, Lincoln marketed the Town Car from 1981 to 2011, with the nameplate previously serving as the flagship trim of the Lincoln Continental. Produced across three generations for thirty model years, the Town Car was marketed directly against luxury sedans from Cadillac and Chrysler.[1]
Marketed nearly exclusively as a four-door sedan (a two-door sedan was offered for 1981 only), many examples of the Town Car were used for fleet and livery (limousine) service. From 1983 to its 2011 discontinuation, the Town Car was the longest car produced by Ford worldwide, becoming the longest mass-production car sold in North America from 1997 to 2011. While not a direct successor of the Town Car, the Lincoln MKS would become the longest American sedan until 2016 (overtaken by the Cadillac CT6).
From 1980 until 2007, the Lincoln Town Car was assembled in Wixom, Michigan, (Wixom Assembly) alongside the Lincoln Continental, LS, and Mark VI, VII, and VIII. After Wixom's closure, Town Car production moved to Southwold, Ontario, (St. Thomas Assembly) alongside the similar Ford Crown Victoria and the Mercury Grand Marquis. The final Lincoln Town Car was produced on August 29, 2011.[2]
Within the Lincoln model line, the Town Car was not directly replaced; the nameplate was used from 2012 to 2019 to denote livery/limousine/hearse variants of the Lincoln MKT. For 2017, the revived Continental replaced the MKS, closely matching the Town Car in wheelbase and width.
"""

APPLES = """
An apple is a round, edible fruit produced by an apple tree (Malus spp., among them the domestic or orchard apple; Malus domestica). Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus. The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found. Apples have been grown for thousands of years in Eurasia and were introduced to North America by European colonists. Apples have religious and mythological significance
in many cultures, including Norse, Greek, and European Christian tradition.
Apples grown from seed tend to be very different from those of their parents, and the resultant fruit frequently lacks desired characteristics. For commercial purposes, including botanical evaluation, apple cultivars are propagated by clonal grafting onto rootstocks. Apple trees grown without rootstocks tend to be larger and much slower to fruit after planting. Rootstocks are used to control the speed of growth and the size of the resulting tree, allowing for easier harvesting.
There are more than 7,500 cultivars of apples. Different cultivars are bred for various tastes and uses, including cooking, eating raw, and cider or apple juice production. Trees and fruit are prone to fungal, bacterial, and pest problems, which can be controlled by a number of organic and non-organic means. In 2010, the fruit's genome was sequenced as part of research on disease control and selective breeding in apple production.
"""


HEBREW = """
Hebrew (Hebrew alphabet: עִבְרִית‎, ʿĪvrīt, pronounced [ivˈʁit] ⓘ or [ʕivˈrit] ⓘ; Samaritan script: ࠏࠨࠁࠬࠓࠪࠉࠕ‎ ʿÎbrit) is a Northwest Semitic language within the Afroasiatic language family. A regional dialect of the Canaanite languages, it was natively spoken by the Israelites and remained in regular use as a first language until after 200 CE and as the liturgical language of Judaism (since the Second Temple period) and Samaritanism.[14] The language was revived as a spoken language in the 19th century, and is the only successful large-scale example of linguistic revival. It is the only Canaanite language, as well as one of only two Northwest Semitic languages, with the other being Aramaic, still spoken today.[15][16]
The earliest examples of written Paleo-Hebrew date back to the 10th century BCE.[17] Nearly all of the Hebrew Bible is written in Biblical Hebrew, with much of its present form in the dialect that scholars believe flourished around the 6th century BCE, during the time of the Babylonian captivity. For this reason, Hebrew has been referred to by Jews as Lashon Hakodesh (לְשׁוֹן הַקֹּדֶש, lit. 'the holy tongue' or 'the tongue [of] holiness') since ancient times. The language was not referred to by the name Hebrew in the Bible, but as Yehudit (transl. 'Judean') or Səpaṯ Kəna'an (transl. "the language of Canaan").[1][note 2] Mishnah Gittin 9:8 refers to the language as Ivrit, meaning Hebrew; however, Mishnah Megillah refers
 to the language as Ashurit, meaning Assyrian, which is derived from the name of the alphabet used, in contrast to Ivrit, meaning the Paleo-Hebrew alphabet.[18]
Hebrew ceased to be a regular spoken language sometime between 200 and 400 CE, as it declined in the aftermath of the unsuccessful Bar Kokhba revolt, which was carried out against the Roman Empire by the Jews of Judaea.[19][20][note 3] Aramaic and, to a lesser extent, Greek were already in use as international languages, especially among societal elites and immigrants.[22] Hebrew survived into the medieval period as the language of Jewish liturgy, rabbinic literature, intra-Jewish commerce, and Jewish poetic literature. The first dated book printed in Hebrew was published by Abraham Garton in Reggio (Calabria, Italy) in 1475.[23]
With the rise of Zionism in the 19th century, the Hebrew language experienced a full-scale revival as a spoken and literary language. The creation of a modern version of the ancient language was led by Eliezer Ben-Yehuda. Modern Hebrew (Ivrit) became the main language of the Yishuv in Palestine, and subsequently the official language of the State of Israel. Estimates of worldwide usage include five million speakers in 1998,[4] and over nine million people in 2013.[24] After Israel, the United States has the largest Hebrew-speaking population, with approximately 220,000 fluent speakers (see Israeli Americans and Jewish Americans).[25]
Modern Hebrew is the official language of the State of Israel,[26][27] while pre-revival forms of Hebrew are used for prayer or study in Jewish and Samaritan communities around the world today; the latter group utilizes the Samaritan dialect as their liturgical tongue. As a non-first language, it is studied mostly by non-Israeli Jews and students in Israel, by archaeologists and linguists specializing in the Middle East and its civilizations, and by theologians in Christian seminaries.
"""

SAMPLE_DATA = [
    LINCOLN_TOWN_CAR,
    HEBREW,
    APPLES,
]
