# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC

"""
Connectors HTTP API. Backend is stateless beyond Composio's own record;
session identity comes from the X-Session-Id header (a UUID generated by
the frontend on first load).
"""

import os
from urllib.parse import urlencode

from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from shared_config.logger_config import get_logger

from .catalog import AVAILABLE_CONNECTORS, get_connector
from .composio_client import (
    ComposioError,
    ComposioNotConfigured,
    delete_connection,
    initiate_oauth,
    list_connections,
)

logger = get_logger(__name__)

SESSION_HEADER = "X-Session-Id"


def _session_id(request) -> str | None:
    raw = request.headers.get(SESSION_HEADER) or request.META.get("HTTP_X_SESSION_ID")
    if not raw:
        return None
    raw = raw.strip()
    return raw or None


def _frontend_callback_url(provider: str, params: dict) -> str:
    base = os.environ.get("CONNECTORS_FRONTEND_CALLBACK_URL", "/connectors/callback")
    query = urlencode({"provider": provider, **params})
    return f"{base}?{query}"


def _backend_callback_url(provider: str, session_id: str) -> str:
    """Where Composio redirects after the user grants OAuth.

    The session id is round-tripped so the callback can attribute the
    connection back to the originating browser even though Composio doesn't
    pass headers through the redirect.
    """
    base = os.environ.get("CONNECTORS_BACKEND_CALLBACK_URL", "").rstrip("/")
    if not base:
        return f"/connectors-api/oauth/callback/?provider={provider}&session_id={session_id}"
    return f"{base}/connectors-api/oauth/callback/?provider={provider}&session_id={session_id}"


@method_decorator(csrf_exempt, name="dispatch")
class AvailableConnectorsView(APIView):
    """GET /connectors-api/available/ — static catalog (no session required)."""

    def get(self, request, *args, **kwargs):
        return Response(
            {"connectors": [spec.to_dict() for spec in AVAILABLE_CONNECTORS]},
            status=status.HTTP_200_OK,
        )


@method_decorator(csrf_exempt, name="dispatch")
class ConnectionsView(APIView):
    """GET /connectors-api/connections/ — list connections for this session.

    Composio is the source of truth. We do not cache connection rows
    server-side; each call lists from Composio filtered by user_id.
    """

    def get(self, request, *args, **kwargs):
        session_id = _session_id(request)
        if not session_id:
            return Response(
                {"error": f"{SESSION_HEADER} header required"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        try:
            connections = list_connections(session_id)
        except ComposioNotConfigured as e:
            return Response({"error": str(e)}, status=status.HTTP_503_SERVICE_UNAVAILABLE)
        except ComposioError as e:
            return Response({"error": str(e)}, status=status.HTTP_502_BAD_GATEWAY)

        slug_by_toolkit = {
            spec.composio_toolkit: spec.slug for spec in AVAILABLE_CONNECTORS
        }
        normalized = []
        for c in connections:
            toolkit_slug = c.get("toolkit_slug")
            provider_slug = slug_by_toolkit.get(toolkit_slug, toolkit_slug)
            normalized.append(
                {
                    "id": c.get("id"),
                    "provider": provider_slug,
                    "status": c.get("status"),
                }
            )
        return Response({"connections": normalized}, status=status.HTTP_200_OK)


@method_decorator(csrf_exempt, name="dispatch")
class ConnectView(APIView):
    """POST /connectors-api/connect/{provider}/ — initiate OAuth."""

    def post(self, request, provider, *args, **kwargs):
        session_id = _session_id(request)
        if not session_id:
            return Response(
                {"error": f"{SESSION_HEADER} header required"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        spec = get_connector(provider)
        if not spec:
            return Response(
                {"error": f"Unknown connector: {provider}"},
                status=status.HTTP_404_NOT_FOUND,
            )
        auth_config_id = spec.auth_config_id()
        if not auth_config_id:
            return Response(
                {
                    "error": (
                        f"{spec.name} is not configured on this server "
                        f"(missing env {spec.auth_config_env})."
                    )
                },
                status=status.HTTP_503_SERVICE_UNAVAILABLE,
            )

        callback_url = _backend_callback_url(spec.slug, session_id)
        try:
            result = initiate_oauth(
                user_id=session_id,
                auth_config_id=auth_config_id,
                callback_url=callback_url,
            )
        except ComposioNotConfigured as e:
            return Response({"error": str(e)}, status=status.HTTP_503_SERVICE_UNAVAILABLE)
        except ComposioError as e:
            return Response({"error": str(e)}, status=status.HTTP_502_BAD_GATEWAY)

        return Response(
            {
                "connection_id": result["id"],
                "auth_url": result["redirect_url"],
                "status": result["status"],
            },
            status=status.HTTP_200_OK,
        )


@method_decorator(csrf_exempt, name="dispatch")
class DisconnectView(APIView):
    """DELETE /connectors-api/connections/{provider}/ — disconnect all of provider."""

    def delete(self, request, provider, *args, **kwargs):
        session_id = _session_id(request)
        if not session_id:
            return Response(
                {"error": f"{SESSION_HEADER} header required"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        spec = get_connector(provider)
        if not spec:
            return Response(
                {"error": f"Unknown connector: {provider}"},
                status=status.HTTP_404_NOT_FOUND,
            )
        try:
            connections = list_connections(session_id, [spec.composio_toolkit])
            for c in connections:
                if c.get("id"):
                    delete_connection(c["id"])
        except ComposioNotConfigured as e:
            return Response({"error": str(e)}, status=status.HTTP_503_SERVICE_UNAVAILABLE)
        except ComposioError as e:
            return Response({"error": str(e)}, status=status.HTTP_502_BAD_GATEWAY)

        return Response({"deleted": len(connections)}, status=status.HTTP_200_OK)


@method_decorator(csrf_exempt, name="dispatch")
class OAuthCallbackView(APIView):
    """GET /connectors-api/oauth/callback/?provider=...&session_id=...

    Composio redirects here after the user grants OAuth. We don't store
    anything — Composio already updated the connection state. We just
    bounce the user to the frontend popup page so it can postMessage to
    its opener and close.
    """

    def get(self, request, *args, **kwargs):
        provider = request.GET.get("provider", "")
        connection_status = request.GET.get("status", "success")
        error = request.GET.get("error", "")

        params = {"status": connection_status}
        if error:
            params["error"] = error

        return HttpResponseRedirect(_frontend_callback_url(provider, params))
