# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: © 2024 Tenstorrent AI ULC

"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from shared_config.backend_config import backend_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-default")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "0.0.0.0",
    "127.0.0.1",
    "localhost",
    os.environ["BACKEND_API_HOSTNAME"],
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Frontend server address
    "http://127.0.0.1:3000",
    "http://0.0.0.0:3000",
]
CORS_ALLOW_ALL_ORIGINS = False

# Add explicit CORS header settings for SSE
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'accept',
]
# Allow credentials for EventSource with withCredentials: true
CORS_ALLOW_CREDENTIALS = True
# Allow streaming responses
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.staticfiles",
    "docker_control.apps.DockerControlConfig",
    "model_control",
    "vector_db_control",
    "corsheaders",
    "logs_control",
    "board_control",
    "workflow_control.apps.WorkflowControlConfig",
    "channels",
    "wakeword_control",
    "training_control",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"
ASGI_APPLICATION = "api.asgi.application"

CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
}

# Database – SQLite for lightweight ORM models (workflow storage, etc.)
# Lives in the persistent volume rather than the bind-mounted source tree, so
# the file never lands root-owned in the repo and --purge-all removes it.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(backend_config.backend_cache_root) / "db.sqlite3",
    }
}

# local memory thread-safe default
# the LOCATION for locmem.LocMemCache cache backend is just a name for tracking
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "default",
    },
    backend_config.django_deploy_cache_name: {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": backend_config.django_deploy_cache_name,
        "KEY_PREFIX": "",  # Set to an empty string to avoid using a prefix
        "VERSION": "version",  # Set to string so it can be stripped
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CHROMA_DB_PORT = int(os.environ.get("CHROMA_DB_PORT", 8111))
CHROMA_DB_HOST = os.environ.get("CHROMA_DB_HOST", "tt_studio_chromadb")
CHROMA_DB_EMBED_MODEL = os.environ.get("CHROMA_DB_EMBED_MODEL", "all-MiniLM-L6-v2")

# Optional cosine-distance ceiling for RAG queries. When set, query results whose
# distance exceeds this value are dropped as insufficiently relevant. Unset (None)
# preserves the previous behavior of always returning the top-N matches.
_rag_relevance_threshold = os.environ.get("RAG_RELEVANCE_THRESHOLD")
RAG_RELEVANCE_THRESHOLD = (
    float(_rag_relevance_threshold) if _rag_relevance_threshold else None
)

# Rewrite the user's query with the deployed LLM before retrieval (adds one LLM
# round-trip per RAG query; skipped automatically when no LLM is deployed).
RAG_QUERY_REWRITE = os.environ.get("RAG_QUERY_REWRITE", "false").strip().lower() in (
    "1",
    "true",
    "yes",
)
# Approximate token cap (chars/4) for the context returned by /collections/retrieve.
RAG_CONTEXT_TOKEN_BUDGET = int(os.environ.get("RAG_CONTEXT_TOKEN_BUDGET") or 2000)
# Cross-encoder reranking of retrieval candidates; auto-skips if the ONNX model
# is unavailable (e.g. offline first boot).
RAG_RERANK_ENABLED = os.environ.get("RAG_RERANK_ENABLED", "true").strip().lower() not in (
    "0",
    "false",
    "no",
)
# Reranked chunks scoring below this (0-1 sigmoid) are dropped...
RAG_RERANK_MIN_SCORE = float(os.environ.get("RAG_RERANK_MIN_SCORE") or 0.05)
# ...but the best N chunks always survive the threshold, so retrieval never
# returns empty just because the cross-encoder scored a niche corpus low.
RAG_RERANK_FLOOR = int(os.environ.get("RAG_RERANK_FLOOR") or 2)
# Chunking for uploaded documents and the internal corpus. all-MiniLM-L6-v2
# truncates input around 256 tokens, so keep chunks small. Changing either
# value reseeds the internal knowledge collection on next startup.
RAG_CHUNK_SIZE = int(os.environ.get("RAG_CHUNK_SIZE") or 750)
RAG_CHUNK_OVERLAP = int(os.environ.get("RAG_CHUNK_OVERLAP") or 100)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
    "UNAUTHENTICATED_USER": None,
}
