# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC

# Generated by Django 5.0.4 on 2025-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('container_name', models.CharField(db_index=True, max_length=255)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('device', models.CharField(max_length=50)),
                ('deployed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='running', max_length=50)),
                ('stopped_by_user', models.BooleanField(default=False)),
                ('port', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-deployed_at'],
                'indexes': [models.Index(fields=['status', '-deployed_at'], name='docker_cont_status_a5afde_idx'), models.Index(fields=['model_name', '-deployed_at'], name='docker_cont_model_n_2ecff9_idx')],
            },
        ),
    ]
