# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC

# Generated by Django 5.0.4 on 2025-11-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldeployment',
            name='workflow_log_path',
            field=models.CharField(blank=True, help_text='Path to workflow log file from tt-inference-server', max_length=512, null=True),
        ),
    ]
