# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC

"""Jira ticket creation for web-UI bug reports.

Files a Bug in the team's Jira project (default DEVSTACK) with the diagnostics
bundle attached, routed to the owning component per
shared_config/component_owners.json (which mirrors .github/CODEOWNERS).

CLI twin: tt_setup/jira_report.py — keep the two in sync. Uses Jira Cloud REST
API v2 (plain wiki-markup description; no ADF needed).
"""

import json
import os
import re

import requests

JIRA_API_BASE = "/rest/api/2"
_TIMEOUT = 15
_OWNER_TABLE_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "shared_config",
    "component_owners.json",
)


def load_jira_config():
    """Jira connection settings from backend_config, or None when the required
    credentials (email + API token) aren't configured."""
    from shared_config.backend_config import backend_config

    if not backend_config.jira_email or not backend_config.jira_api_token:
        return None
    return {
        "url": (backend_config.jira_url or "https://tenstorrent.atlassian.net").rstrip("/"),
        "email": backend_config.jira_email,
        "token": backend_config.jira_api_token,
        "project_key": backend_config.jira_project_key or "DEVSTACK",
    }


def load_owner_table(path=_OWNER_TABLE_PATH):
    """Component→owner routing table; {} when unreadable (classifier then
    degrades to its built-in 'unknown')."""
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return {}


def classify_component(table, error_log_sources=()):
    """Map error-bearing log sources to a component key from the owner table.

    The web-UI path has no traceback; classification uses which collected log
    sources contain errors, in the order the caller passes them.
    """
    components = table.get("components", {})
    default = table.get("default", "unknown")
    for source in error_log_sources:
        for key, entry in components.items():
            if source in entry.get("log_sources", []):
                return key
    return default


def error_bearing_sources(named_texts):
    """Names from (name, text) pairs whose tail mentions an error, for the
    classifier's log-source pass."""
    hits = []
    for name, text in named_texts:
        tail = "\n".join((text or "").splitlines()[-200:])
        if re.search(r"error|traceback|exception", tail, re.IGNORECASE):
            hits.append(name)
    return hits


def build_summary(ref, title=""):
    summary = title.strip() or "web report"
    return f"tt-studio: bug report [{ref}] — {summary}"[:150]


def build_wiki_description(ref, form, component, entry):
    """Jira wiki-markup ticket body from the Bug Report modal's form fields."""
    owners = ", ".join(f"@{o}" for o in entry.get("github_owners", [])) or "unassigned"
    sections = [
        "h3. Bug Report",
        "",
        f"*Reference:* {{{{{ref}}}}}",
        f"*Component:* {component} (owners: {owners})",
    ]
    for heading, key in (
        ("Description", "description"),
        ("Steps to Reproduce", "steps"),
        ("Expected Behavior", "expected"),
        ("Actual Behavior", "actual"),
    ):
        value = (form.get(key) or "").strip()
        if value:
            sections += ["", f"h3. {heading}", "", value]
    sections += [
        "",
        "----",
        f"Diagnostics bundle {{{{tt-studio-logs-{ref}.zip}}}} is attached.",
        "_Auto-generated by the TT-Studio web UI (Report Bug)._",
    ]
    return "\n".join(sections)


def _auth(cfg):
    return (cfg["email"], cfg["token"])


def find_account_id(cfg, email):
    """Resolve a Jira Cloud accountId from an email; None when the user can't be
    found (e.g. email hidden by privacy settings) — ticket then stays unassigned."""
    resp = requests.get(
        f"{cfg['url']}{JIRA_API_BASE}/user/search",
        params={"query": email},
        auth=_auth(cfg),
        timeout=_TIMEOUT,
    )
    if resp.status_code != 200:
        return None
    users = resp.json()
    return users[0].get("accountId") if users else None


def create_jira_issue(cfg, summary, description, labels, account_id=None):
    """Create the Bug and return (issue_key, browse_url). Raises on API errors
    (caller decides the fallback)."""
    fields = {
        "project": {"key": cfg["project_key"]},
        "issuetype": {"name": "Bug"},
        "summary": summary,
        "description": description,
        "labels": labels,
    }
    if account_id:
        fields["assignee"] = {"accountId": account_id}
    resp = requests.post(
        f"{cfg['url']}{JIRA_API_BASE}/issue",
        json={"fields": fields},
        auth=_auth(cfg),
        timeout=_TIMEOUT,
    )
    resp.raise_for_status()
    key = resp.json()["key"]
    return key, f"{cfg['url']}/browse/{key}"


def attach_zip_bytes(cfg, issue_key, zip_bytes, filename):
    """Attach the diagnostics bundle to the ticket. True on success."""
    resp = requests.post(
        f"{cfg['url']}{JIRA_API_BASE}/issue/{issue_key}/attachments",
        files={"file": (filename, zip_bytes, "application/zip")},
        headers={"X-Atlassian-Token": "no-check"},
        auth=_auth(cfg),
        timeout=60,
    )
    return resp.status_code == 200
