name: ORT SPDX License Compliance Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - staging
    types:
    - opened
    - reopened
    - synchronize
    - assigned
    - review_requested
  

jobs:
  ort-license-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ORT Analysis
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          ort-cli-args: 'analyze -i . -o ort-results'

      - name: Run ORT Report Generation
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          ort-cli-args: 'report -i ort-results/analyzer-result.yml -o ort-results/reports'

      - name: Upload ORT Results
        uses: actions/upload-artifact@v3
        with:
          name: ort-results
          path: ort-results

      - name: Show ORT Results Summary
        if: always()
        run: |
          cat ort-results/analyzer-result.yml
